// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHbbR7XHCfXmtQIK2ZMSM1HaRpLULtNUg',
    appId: '1:308755484224:web:65122a076b276d743ad9a5',
    messagingSenderId: '308755484224',
    projectId: 'my-fb-project-5d61d',
    authDomain: 'my-fb-project-5d61d.firebaseapp.com',
    storageBucket: 'my-fb-project-5d61d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCfQLGx-TAJIwk8-FTruPgXGXeoh9nSFOA',
    appId: '1:308755484224:android:13ae6bd919eaf64b3ad9a5',
    messagingSenderId: '308755484224',
    projectId: 'my-fb-project-5d61d',
    storageBucket: 'my-fb-project-5d61d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDQlQ0yDussPob8fmyvB2iOm68fNzryEL8',
    appId: '1:308755484224:ios:ebd2bf6a2ab0563c3ad9a5',
    messagingSenderId: '308755484224',
    projectId: 'my-fb-project-5d61d',
    storageBucket: 'my-fb-project-5d61d.firebasestorage.app',
    iosBundleId: 'com.example.myFbProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDQlQ0yDussPob8fmyvB2iOm68fNzryEL8',
    appId: '1:308755484224:ios:ebd2bf6a2ab0563c3ad9a5',
    messagingSenderId: '308755484224',
    projectId: 'my-fb-project-5d61d',
    storageBucket: 'my-fb-project-5d61d.firebasestorage.app',
    iosBundleId: 'com.example.myFbProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHbbR7XHCfXmtQIK2ZMSM1HaRpLULtNUg',
    appId: '1:308755484224:web:dc2c906910791dd33ad9a5',
    messagingSenderId: '308755484224',
    projectId: 'my-fb-project-5d61d',
    authDomain: 'my-fb-project-5d61d.firebaseapp.com',
    storageBucket: 'my-fb-project-5d61d.firebasestorage.app',
  );
}
